using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace CurrencyConverterDotNet;

public static class CurrencyCodeExtensions
{
    public static string[] Names = {
        "Unrecognized/Uninitialized Currency",
        "United Arab Emirates dirham",
        "Afghan afghani",
        "Albanian lek",
        "Armenian dram",
        "Netherlands Antillean guilder",
        "Angolan kwanza",
        "Argentine peso",
        "Australian dollar",
        "Azerbaijani manat",
        "Bosnia and Herzegovina convertible mark",
        "Barbados dollar",
        "Bangladeshi taka",
        "Bulgarian lev",
        "Bahraini dinar",
        "Burundian franc",
        "Bermudian dollar",
        "Brunei dollar",
        "Boliviano",
        "Brazilian real",
        "Bahamian dollar",
        "Botswana pula",
        "New Belarusian ruble",
        "Belize dollar",
        "Canadian dollar",
        "Congolese franc",
        "Swiss franc",
        "Chilean peso",
        "Renminbi|Chinese yuan",
        "Colombian peso",
        "Costa Rican colon",
        "Cuban convertible peso",
        "Cuban peso",
        "Cape Verde escudo",
        "Czech koruna",
        "Djiboutian franc",
        "Danish krone",
        "Dominican peso",
        "Algerian dinar",
        "Egyptian pound",
        "Eritrean nakfa",
        "Ethiopian birr",
        "Euro",
        "Fiji dollar",
        "Pound sterling",
        "Georgian lari",
        "Ghanaian cedi",
        "Gambian dalasi",
        "Guinean franc",
        "Guatemalan quetzal",
        "Guyanese dollar",
        "Hong Kong dollar",
        "Honduran lempira",
        "Haitian gourde",
        "Hungarian forint",
        "Indonesian rupiah",
        "Israeli new shekel",
        "Indian rupee",
        "Iraqi dinar",
        "Iranian rial",
        "Icelandic króna",
        "Jamaican dollar",
        "Jordanian dinar",
        "Japanese yen",
        "Kenyan shilling",
        "Kyrgyzstani som",
        "Cambodian riel",
        "Comoro franc",
        "South Korean won",
        "Kuwaiti dinar",
        "Cayman Islands dollar",
        "Kazakhstani tenge",
        "Lao kip",
        "Lebanese pound",
        "Sri Lankan rupee",
        "Liberian dollar",
        "Lesotho loti",
        "Libyan dinar",
        "Moroccan dirham",
        "Moldovan leu",
        "Malagasy ariary",
        "Macedonian denar",
        "Myanmar kyat",
        "Mongolian tögrög",
        "Mauritanian ouguiya",
        "Mauritian rupee",
        "Maldivian rufiyaa",
        "Malawian kwacha",
        "Mexican peso",
        "Malaysian ringgit",
        "Mozambican metical",
        "Namibian dollar",
        "Nigerian naira",
        "Nicaraguan córdoba",
        "Norwegian krone",
        "Nepalese rupee",
        "New Zealand dollar",
        "Omani rial",
        "Peruvian Sol",
        "Papua New Guinean kina",
        "Philippine peso",
        "Pakistani rupee",
        "Polish złoty",
        "Paraguayan guaraní",
        "Qatari riyal",
        "Romanian leu",
        "Serbian dinar",
        "Russian ruble",
        "Rwandan franc",
        "Saudi riyal",
        "Solomon Islands dollar",
        "Seychelles rupee",
        "Sudanese pound",
        "Swedish krona",
        "Singapore dollar",
        "Sierra Leonean leone",
        "Somali shilling",
        "Surinamese dollar",
        "South Sudanese pound",
        "São Tomé and Príncipe dobra",
        "Salvadoran colón",
        "Syrian pound",
        "Swazi lilangeni",
        "Thai baht",
        "Tajikistani somoni",
        "Turkmenistani manat",
        "Tunisian dinar",
        "Tongan paʻanga",
        "Turkish lira",
        "Trinidad and Tobago dollar",
        "New Taiwan dollar",
        "Tanzanian shilling",
        "Ukrainian hryvnia",
        "Ugandan shilling",
        "United States dollar",
        "Uruguayan peso",
        "Uzbekistan som",
        "Venezuelan bolívar",
        "Vietnamese đồng",
        "Vanuatu vatu",
        "Samoan tala",
        "Central African CFA franc",
        "East Caribbean dollar",
        "West African CFA franc",
        "Yemeni rial",
        "South African rand",
        "Zambian kwacha",
        "Zimbabwean dollar"
    };
    public static string[] CountryCurrencyDesc = {
        "Unrecognized/Uninitialized Currency",
        "United Arab Emirates-Dirham",
        "Afghanistan-Afghani",
        "Albania-Lek",
        "Armenia-Dram",
        "Netherlands Antilles-Guilder",
        "Angola-Kwanza",
        "Argentina-Peso",
        "Australia-Dollar",
        "Azerbaijan-Manat",
        "Bosnia-Marka",
        "Barbados-Dollar",
        "Bangladesh-Taka",
        "Bulgaria-Lev New",
        "Bahrain-Dinar",
        "Burundi-Franc",
        "Bermuda-Dollar",
        "Brunei-Dollar",
        "Bolivia-Boliviano",
        "Brazil-Real",
        "Bahamas-Dollar",
        "Botswana-Pula",
        "Belarus-New Ruble",
        "Belize-Dollar",
        "Canada-Dollar",
        "Congo-CFA Franc",
        "Switzerland-Franc",
        "Chile-Peso",
        "China-Renminbi",
        "Colombia-Peso",
        "Costa Rica-Colon",
        "Cuba-Chavito",
        "Cuba-Peso",
        "Cape Verde-Escudo",
        "Czech Republic-Koruna",
        "Djibouti-Franc",
        "Denmark-Krone",
        "Dominican Republic-Peso",
        "Algeria-Dinar",
        "Egypt-Pound",
        "Eritrea-Nakfa",
        "Ethiopia-Birr",
        "Euro Zone-Euro",
        "Fiji-Dollar",
        "United Kingdom-Pound",
        "Georgia-Lari",
        "Ghana-Cedi",
        "Gambia-Dalasi",
        "Guinea-Franc",
        "Guatemala-Quentzal",
        "Guyana-Dollar",
        "Hong Kong-Dollar",
        "Honduras-Lempira",
        "Haiti-Gourde",
        "Hungary-Forint",
        "Indonesia-Rupiah",
        "Israel-Shekel",
        "India-Rupee",
        "Iraq-Dinar",
        "Iran-Rial",
        "Iceland-Krona",
        "Jamaica-Dollar",
        "Jordan-Dinar",
        "Japan-Yen",
        "Kenya-Shilling",
        "Kyrgyzstan-Som",
        "Cambodia-Riel",
        "Comoros-Franc",
        "Korea-Won",
        "Kuwait-Dinar",
        "Cayman Islands-Dollar",
        "Kazakhstan-Tenge",
        "Laos-Kip",
        "Lebanon-Pound",
        "Sri Lanka-Rupee",
        "Liberia-Dollar",
        "Lesotho-Maloti",
        "Libya-Dinar",
        "Morocco-Dirham",
        "Moldova-LEU",
        "Madagascar-Ariary",
        "Rep. of N. Macedonia-Denar",
        "Myanmar-Kyat",
        "Mongolia-Tugrik",
        "Mauritania-Ouguiya",
        "Mauritius-Rupee",
        "Maldives-Rufiyaa",
        "Malawi-Kwacha",
        "Mexico-Peso",
        "Malaysia-Ringgit",
        "Mozambique-Metical",
        "Nambia-Dollar",
        "Nigeria-Naira",
        "Nicaragua-Cordoba",
        "Norway-Krone",
        "Nepal-Rupee",
        "New Zealand-Dollar",
        "Oman-Rial",
        "Peru-Sol",
        "Papua New Guinea-Kina",
        "Philippines-Peso",
        "Pakistan-Rupee",
        "Poland-Zloty",
        "Paraguay-Guarani",
        "Qatar-Riyal",
        "Romania-New Leu",
        "Serbia-Dinar",
        "Russia-Ruble",
        "Rwanda-Franc",
        "Saudi Arabia-Riyal",
        "Solomon Islands-Dollar",
        "Seychelles-Rupee",
        "Sudan-Pound",
        "Sweden-Krona",
        "Singapore-Dollar",
        "Sierra Leone-Leone",
        "Somali-Shilling",
        "Suriname-Dollar",
        "South Sudan-Sudanese Pound",
        "Sao Tome & Principe-New Dobras",
        "El Salvador-Dollar",
        "Syria-Pound",
        "Eswatini-Lilangeni",
        "Thailand-Baht",
        "Tajikistan-Somoni",
        "Turkmenistan-New Manat",
        "Tunisia-Dinar",
        "Tonga-Pa'anga",
        "Turkey-New Lira",
        "Trinidad & Tobago-Dollar",
        "Taiwan-Dollar",
        "Tanzania-Shilling",
        "Ukraine-Hryvnia",
        "Uganda-Shilling",
        "United States of America-Dollar",
        "Uruguay-Peso",
        "Uzbekistan-Som",
        "Venezuela-Bolivar Soberano",
        "Vietnam-Dong",
        "Vanuatu-Vatu",
        "Western Samoa-Tala",
        "Central African Rep.-CFA Franc",
        "Grenada-E.Caribbean Dollar",
        "Benin-CFA Franc",
        "Yemen-Rial",
        "South Africa-Rand",
        "Zambia-New Kwacha",
        "Zimbabwe-RTGS"
    };
    /// <summary>
    /// string GetCode(CurrencyCode code): Retrieve 3-letter currency code
    ///    abbreviation of the enum variant CurrencyCode in argument
    /// </summary>
    /// <param name="code"></param>
    /// <returns>
    /// string 'abbr', abbreviated code of the currently initialized
    ///    variant of CurrencyCode enum
    /// </returns>
    public static String GetCode(CurrencyCode code)
    {
        return Enum.GetName(typeof(CurrencyCode), (int)code);
    }
    /// <summary>
    /// CurrencyCode FromText(string text): Enum variant initializer from
    ///    input parameter 'text' case insensitive 3-letter currency code
    /// </summary>
    /// <param name="text"></param>
    /// <returns>
    /// enum CurrencyCode.'text', if 'text' is an implemented variant.
    ///    enum CurrencyCode.NONE if currency option 'text' isn't available.
    ///    Call GetOptions() to view all implemented variants.
    /// </returns>                    
    public static CurrencyCode FromText(string text) {
        string[] codesArray = Enum.GetNames(typeof(CurrencyCode));
        for (int i=0; i<codesArray.Length; i++)
        {
            if ( codesArray[i] == text.ToUpper() ) 
            {
                return (CurrencyCode) i;
            }
        };
        return CurrencyCode.NONE;
    }
    /// <summary>
    /// string[] GetOptions(): Retrieve implemented enum variant names.
    /// </summary>
    /// <returns>
    /// string[] GetOptions(): Array with elements 1..N implemented variant names
    ///    sorted in alphabetical order. Element 0 is uninitialized value 'NONE'.
    /// </returns>
    public static string[] GetOptions()
    {
        
        return Enum.GetNames(typeof(CurrencyCode));
    }
    /// <summary>
    /// string GetName(CurrencyCode code): Retrieve legible currency name from
    ///    enum variant CurrencyCode in argument
    /// </summary>
    /// <param name="code"></param>
    /// <returns>
    /// string 'name', legible currency name (and issuing entity if applicable)
    ///    for initialized variant of CurrencyCode enum
    /// </returns>
    public static String GetName(CurrencyCode code)
    {
        return Names[(int) code];
    }
}

public enum CurrencyCode {
    NONE,
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BWP,
    BYN,
    BZD,
    CAD,
    CDF,
    CHF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    GBP,
    GEL,
    GHS,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MRO,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SLL,
    SOS,
    SRD,
    SSP,
    STD,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UZS,
    VED,
    VND,
    VUV,
    WST,
    XAF,
    XCD,
    XOF,
    YER,
    ZAR,
    ZMW,
    ZWL
}
